version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add build-base bsd-compat-headers lua5.3-dev luarocks
      - run: apk add openssl-dev zlib-dev m4 gawk musl
      - run: luarocks-5.3 install busted
      - run: luarocks-5.3 make
      - run: busted --run=ci